#!/bin/sh

npm --silent run play "node ./src/cli/adapter.js carefulPlayer" "node ./src/cli/adapter.js carefulPlayer" "node ./src/cli/adapter.js carefulPlayer" "node ./src/cli/adapter.js carefulPlayer" 2
